using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Stratum.Editor
{
    internal static class ManagerCreationService
    {
        private const string GeneratedConfigListFieldName = "_configs";

        public static void CreateManager(ManagerCreatorState state)
        {
            if (state == null || !state.IsValid) return;
            CreateManager(state.BuildPlan());
        }

        public static bool TryCreateManagerInParentFolder(string parentAssetPath, string managerName, out string errorMessage)
        {
            var state = new ManagerCreatorState();
            state.SetInputWithParentFolder(parentAssetPath, managerName);
            if (!state.IsValid) { errorMessage = state.ErrorMessage; return false; }

            CreateManager(state);
            errorMessage = null;
            return true;
        }

        private static void CreateManager(ManagerCreationPlan plan)
        {
            var configTypeAvailable = plan.IncludeConfig && FindType(plan.ConfigClassName) != null;

            if (plan.ShouldCreateManagerFile) WriteManagerCode(plan);

            EnsureFolder(plan.GeneratedFolderPath);
            WriteManagerPartialGeneratedCode(plan);
            if (plan.IncludeConfig)
            {
                WriteConfigGeneratedCode(plan);
                WriteDataGeneratedCode(plan);
                WriteRefresherCode(plan);
            }

            if (!string.IsNullOrEmpty(plan.EntityFolderPath))
                WriteLeafMarker(plan.EntityFolderPath);

            AssetDatabase.Refresh();

            if (plan.IncludeConfig)
            {
                if (configTypeAvailable)
                    EnsureAssetAndAddressable(plan.ManagerName, plan.AssetFilePath, plan.AddressableAddressName);
                else
                    ManagerPostCompileAssetService.ScheduleAssetCreation(plan);
            }

            ManagerAssetIndex.Invalidate();
        }

        private static void WriteManagerCode(ManagerCreationPlan plan)
        {
            var sb = new StringBuilder();
            if (plan.IncludeConfig) sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Stratum;");
            sb.AppendLine();
            sb.AppendLine($"public interface {plan.ManagerInterfaceName}");
            sb.AppendLine("{");
            sb.AppendLine();
            sb.AppendLine("}");
            sb.AppendLine();

            if (plan.IncludeConfig)
            {
                sb.AppendLine($"internal sealed partial class {plan.ManagerDataStructName}");
                sb.AppendLine("{");
                sb.AppendLine("    public string Key;");
                sb.AppendLine("}");
                sb.AppendLine();
                sb.AppendLine($"internal sealed partial class {plan.ManagerClassName} : {plan.ManagerInterfaceName}");
                sb.AppendLine("{");
                sb.AppendLine($"    private readonly Dictionary<string, {plan.ManagerDataStructName}> _managerDataDict = new();");
                sb.AppendLine("}");
            }
            else
            {
                sb.AppendLine($"internal partial class {plan.ManagerClassName} : {plan.ManagerInterfaceName}");
                sb.AppendLine("{");
                sb.AppendLine();
                sb.AppendLine("}");
            }

            EnsureFolder(Path.GetDirectoryName(plan.ManagerTargetFilePath));
            File.WriteAllText(plan.ManagerTargetFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void WriteConfigGeneratedCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedConfigFilePath)) return;

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Stratum;");
            sb.AppendLine();
            sb.AppendLine($"public sealed partial class {plan.ConfigClassName} : BaseManagerConfig");
            sb.AppendLine("{");
            sb.AppendLine("    [SerializeField]");
            sb.AppendLine($"    private List<{plan.ManagerDataStructName}> {GeneratedConfigListFieldName} = new();");
            sb.AppendLine();
            sb.AppendLine($"    public override Type ConfigItemType => typeof({plan.ManagerDataStructName});");
            sb.AppendLine($"    public override IList GetConfigList() => {GeneratedConfigListFieldName};");
            sb.AppendLine();
            sb.AppendLine($"    protected override Dictionary<string, BaseManagerData> GetManagerDataDict() => {GeneratedConfigListFieldName}");
            sb.AppendLine("        .Where(static c => !string.IsNullOrWhiteSpace(c.Key))");
            sb.AppendLine("        .ToDictionary(static c => c.Key.Trim(), static c => (BaseManagerData)c, StringComparer.Ordinal);");
            sb.AppendLine("}");

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedConfigFilePath));
            File.WriteAllText(plan.GeneratedConfigFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void WriteDataGeneratedCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedDataFilePath)) return;

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb);
            sb.AppendLine("using System;");
            sb.AppendLine("using Stratum;");
            sb.AppendLine();
            sb.AppendLine("[Serializable]");
            sb.AppendLine($"internal sealed partial class {plan.ManagerDataStructName} : BaseManagerData {{ }}");

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedDataFilePath));
            File.WriteAllText(plan.GeneratedDataFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void WriteManagerPartialGeneratedCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedManagerPartialFilePath)) return;

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb);
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using Stratum;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine();

            if (plan.IncludeConfig)
            {
                sb.AppendLine("[Preserve]");
                sb.AppendLine($"internal sealed partial class {plan.ManagerClassName} : BaseManager");
                sb.AppendLine("{");
                sb.AppendLine("    protected override async UniTask SetManagerDataDict()");
                sb.AppendLine("    {");
                sb.AppendLine($"        var config = await FrameworkLoader.LoadAsync<{plan.ConfigClassName}>(\"{EscapeCSharpStringLiteral(plan.AddressableAddressName)}\");");
                sb.AppendLine("        _managerDataDict.Clear();");
                sb.AppendLine("        foreach (var kv in config.ExportManagerDataDict())");
                sb.AppendLine($"            _managerDataDict[kv.Key] = ({plan.ManagerDataStructName})kv.Value;");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }
            else
            {
                sb.AppendLine("[Preserve]");
                sb.AppendLine($"internal partial class {plan.ManagerClassName} : BaseManager");
                sb.AppendLine("{");
                sb.AppendLine("    protected override UniTask SetManagerDataDict() => UniTask.CompletedTask;");
                sb.AppendLine("}");
            }

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedManagerPartialFilePath));
            File.WriteAllText(plan.GeneratedManagerPartialFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void WriteRefresherCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.RefresherFilePath)) return;

            var refresherFolder = Path.GetDirectoryName(plan.RefresherFilePath);
            EnsureFolder(refresherFolder);
            EnsureRefresherAsmref(refresherFolder);

            var abs = Path.GetFullPath(Path.Combine(Application.dataPath, "..", plan.RefresherFilePath));
            if (File.Exists(abs)) return;

            var configAssetPath = plan.AssetFilePath.Replace('\\', '/');

            var sb = new StringBuilder();
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using Stratum;");
            sb.AppendLine("using Stratum.Editor;");
            sb.AppendLine();
            sb.AppendLine($"internal static class {plan.ManagerName}ManagerRefresher");
            sb.AppendLine("{");
            sb.AppendLine($"    private const string ConfigAssetPath = \"{configAssetPath}\";");
            sb.AppendLine();
            sb.AppendLine("    [EditorSync]");
            sb.AppendLine("    public static void Run()");
            sb.AppendLine("    {");
            sb.AppendLine($"        var cfg = AssetDatabase.LoadAssetAtPath<{plan.ConfigClassName}>(ConfigAssetPath);");
            sb.AppendLine("        if (cfg == null) return;");
            sb.AppendLine();
            sb.AppendLine($"        var list = (System.Collections.Generic.List<{plan.ManagerDataStructName}>)cfg.GetConfigList();");
            sb.AppendLine();
            sb.AppendLine("        // TODO: implement the custom refresh logic here.");
            sb.AppendLine();
            sb.AppendLine("        EditorUtility.SetDirty(cfg);");
            sb.AppendLine("        AssetDatabase.SaveAssets();");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(abs, sb.ToString(), Encoding.UTF8);
        }

        private static void EnsureRefresherAsmref(string refresherFolderAssetPath)
        {
            if (string.IsNullOrEmpty(refresherFolderAssetPath)) return;
            var asmrefPath = $"{refresherFolderAssetPath.Replace('\\', '/')}/Game.Editor.asmref";
            var abs = Path.GetFullPath(Path.Combine(Application.dataPath, "..", asmrefPath));
            if (File.Exists(abs)) return;
            File.WriteAllText(abs, "{\n    \"reference\": \"Game.Editor\"\n}\n", Encoding.UTF8);
        }

        private static void WriteLeafMarker(string entityFolderAssetPath)
        {
            var abs = Path.GetFullPath(Path.Combine(Application.dataPath, "..", entityFolderAssetPath, "_leaf.json"));
            var dir = Path.GetDirectoryName(abs);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
            if (!File.Exists(abs)) File.WriteAllText(abs, string.Empty);
        }

        internal static bool EnsureAssetAndAddressable(string managerName, string assetPath, string assetAddress)
        {
            var asset = AssetDatabase.LoadAssetAtPath<ScriptableObject>(assetPath);
            if (asset == null)
            {
                EnsureFolder(Path.GetDirectoryName(assetPath));

                var configType = FindType($"{managerName}ManagerConfig");
                if (configType == null)
                {
                    Debug.LogError($"[ManagerCreationService] Config type not found: {managerName}ManagerConfig");
                    return false;
                }

                asset = ScriptableObject.CreateInstance(configType);
                AssetDatabase.CreateAsset(asset, assetPath);
                AssetDatabase.SaveAssets();
            }

            AddressablesHelper.EnsureEntry(assetPath, assetAddress, ManagerCreatorState.AddressableGroupName);
            ManagerAssetIndex.Invalidate();
            Debug.Log($"[ManagerCreationService] {managerName}Manager created successfully.");
            return true;
        }

        private static void AppendAutoGeneratedHeader(StringBuilder sb)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated. Do not modify manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
        }

        private static string EscapeCSharpStringLiteral(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static Type FindType(string typeName)
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                try { foreach (var t in assembly.GetTypes()) if (t.Name == typeName) return t; }
                catch (ReflectionTypeLoadException e) { foreach (var t in e.Types) if (t != null && t.Name == typeName) return t; }
                catch { }
            }
            return null;
        }

        internal static void EnsureFolder(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath)) return;
            assetPath = assetPath.Replace('\\', '/').TrimEnd('/');
            if (assetPath == "Assets" || AssetDatabase.IsValidFolder(assetPath)) return;

            var parts = assetPath.Split('/');
            for (var i = 1; i < parts.Length; i++)
            {
                var parent = string.Join("/", parts, 0, i);
                var child  = $"{parent}/{parts[i]}";
                if (!AssetDatabase.IsValidFolder(child))
                    AssetDatabase.CreateFolder(parent, parts[i]);
            }
        }
    }

    internal static class ManagerPostCompileAssetService
    {
        private const string PendingTemplatesKey = "ManagerInstaller.PendingTemplates";

        [InitializeOnLoadMethod]
        private static void ProcessPendingAssetCreation()
        {
            // ── Creator 页面挂起的单条 ──────────────────────────────────────────
            var managerName  = SessionState.GetString(ManagerCreatorState.SessionManagerNameKey,  string.Empty);
            var assetPath    = SessionState.GetString(ManagerCreatorState.SessionAssetPathKey,    string.Empty);
            var assetAddress = SessionState.GetString(ManagerCreatorState.SessionAssetAddressKey, string.Empty);

            if (!string.IsNullOrEmpty(managerName) && !string.IsNullOrEmpty(assetPath) && !string.IsNullOrEmpty(assetAddress))
            {
                SessionState.EraseString(ManagerCreatorState.SessionManagerNameKey);
                SessionState.EraseString(ManagerCreatorState.SessionAssetPathKey);
                SessionState.EraseString(ManagerCreatorState.SessionAssetAddressKey);

                EditorApplication.delayCall += () =>
                    ManagerCreationService.EnsureAssetAndAddressable(managerName, assetPath, assetAddress);
            }

            // ── Installer 批量挂起 ───────────────────────────────────────────────
            var pending = SessionState.GetString(PendingTemplatesKey, string.Empty);
            if (string.IsNullOrEmpty(pending)) return;

            SessionState.EraseString(PendingTemplatesKey);
            foreach (var mgrName in pending.Split(','))
            {
                if (string.IsNullOrEmpty(mgrName)) continue;
                var n = mgrName;
                var p = $"{ManagerCreatorState.RootAssetPath}/{n}/{n}ManagerConfig.asset";
                var a = ManagerAddressConvention.AddressOf(n);
                EditorApplication.delayCall += () =>
                    ManagerCreationService.EnsureAssetAndAddressable(n, p, a);
            }
        }

        /// <summary>Creator 页面：挂起单条 asset 创建。</summary>
        public static void ScheduleAssetCreation(ManagerCreationPlan plan)
        {
            SessionState.SetString(ManagerCreatorState.SessionManagerNameKey,  plan.ManagerName);
            SessionState.SetString(ManagerCreatorState.SessionAssetPathKey,    plan.AssetFilePath);
            SessionState.SetString(ManagerCreatorState.SessionAssetAddressKey, plan.AddressableAddressName);
        }

        /// <summary>Installer：批量挂起模板导入后的 asset 创建，编译完成后逐一执行。</summary>
        public static void ScheduleTemplateInstall(string managerName)
        {
            var existing = SessionState.GetString(PendingTemplatesKey, string.Empty);
            var names    = string.IsNullOrEmpty(existing)
                ? new System.Collections.Generic.List<string>()
                : new System.Collections.Generic.List<string>(existing.Split(','));
            if (!names.Contains(managerName)) names.Add(managerName);
            SessionState.SetString(PendingTemplatesKey, string.Join(",", names));
        }
    }

    internal static class ManagerAssetIndex
    {
        private static Dictionary<string, string> _scripts;
        private static Dictionary<string, string> _assets;

        static ManagerAssetIndex()
        {
            EditorApplication.projectChanged -= Invalidate;
            EditorApplication.projectChanged += Invalidate;
        }

        public static string FindManagerScript(string fileName) =>
            Find(ref _scripts, ManagerCreatorState.RootAssetPath, fileName, ".cs");

        public static string FindManagerAsset(string fileName) =>
            Find(ref _assets, ManagerCreatorState.RootAssetPath, fileName, ".asset");

        public static void Invalidate() { _scripts = null; _assets = null; }

        private static string Find(ref Dictionary<string, string> cache, string root, string fileName, string ext)
        {
            if (string.IsNullOrEmpty(fileName)) return null;
            cache ??= BuildIndex(root, ext);
            return cache.TryGetValue(fileName, out var path) ? path : null;
        }

        private static Dictionary<string, string> BuildIndex(string root, string ext)
        {
            var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var guid in AssetDatabase.FindAssets(string.Empty, new[] { root }))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid)?.Replace('\\', '/');
                if (string.IsNullOrEmpty(path) || !path.EndsWith(ext, StringComparison.OrdinalIgnoreCase)) continue;
                var name = Path.GetFileName(path);
                if (!map.ContainsKey(name)) map.Add(name, path);
            }
            return map;
        }
    }
}
